server:
  port: 8086

spring:
  application:
    name: blog-admin

  profiles:
    active: dev

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

