
spring:
##设置数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.212.87:3306/blog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456

logging:
   #log的输出目录
  file: D:\\blog-service-impl.log
   ##日记级别为debug级别
  level: debug













